import {readFile, writeFile, rename} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const {build} = await import(process.env.ESBUILD_MODULE || 'esbuild');
const root = fileURLToPath(new URL('../', import.meta.url));
const {version} = JSON.parse(await readFile(root + 'package.json', 'utf8'));
const license = await readFile(root + 'LICENSE', 'utf8');
const result = await build({
  absWorkingDir: root,
  entryPoints: ['src/index.js'],
  outfile: 'scene-presets-card.js',
  bundle: true,
  splitting: false,
  format: 'esm',
  platform: 'browser',
  target: ['es2022'],
  define: {__SCENE_PRESETS_CARD_VERSION__: JSON.stringify(version)},
  banner: {js: `// Scene Presets Card ${version} — generated by npm run build; edit src/ instead.
/*!
 * SPDX-License-Identifier: Apache-2.0

${license.trimEnd()}
*/`},
  metafile: true,
  write: false,
});
if (result.outputFiles.length !== 1 || Object.values(result.metafile.outputs).some(output => output.imports.length)) {
  throw new Error('Release must be a single file without runtime JavaScript imports.');
}
const target = root + 'scene-presets-card.js';
await writeFile(target + '.tmp', result.outputFiles[0].contents);
await rename(target + '.tmp', target);
console.log(`Built Scene Presets Card ${version}: ${result.outputFiles[0].contents.length} bytes, no runtime module imports.`);
